dist: connected.png copy.png build_run.png git.png my_beaglebone.jpg Makefile README
	tar -cvzf lab4a-204971333.tar.gz connected.png copy.png build_run.png git.png my_beaglebone.jpg Makefile README
	
